### ISSUE TITLE
图片原文件名中如果包含空格，上传到cos后无法被访问

### ISSUE THREAD

**Issue by fengyunhe** [sy-records/sync-qcloud-cos#35]
原文件名： Screenshot from 2023-09-01 11-33-23.png
上传后的URL:  https://blog-1251934191.cos.ap-chengdu.myqcloud.com/wp-content/uploads/2023/09/Screenshot-from-2023-09-01-11-33-23-2-1020x822.png

**Comment by fengyunhe** [comment]
实际并未上传成功，Bucket中没看到

**Comment by sy-records** [comment]
我测试可以，空格为转为`-`，本地和桶里的都能访问

**Comment by sy-records** [comment]
你这看起来是防盗链的问题

<img width="517" alt="image" src="https://github.com/sy-records/sync-qcloud-cos/assets/33931153/f64b408c-e04c-4fd2-9027-600f514cc224">
