### ISSUE TITLE
如果服务器与COS桶通信状况不佳，上传会失败

### ISSUE THREAD

**Issue by MIKU-N** [sy-records/sync-qcloud-cos#43]
RT,我的服务器是甲骨文日本的ARM服务器，而储存桶选了国内。
我发现在服务器与大陆的通信状况较差的情况下，如果服务器操作文件上传超时，那么文件就必须重传了，因为插件不会再次尝试上传（即使文件已经传到服务器上了
![image](https://github.com/sy-records/sync-qcloud-cos/assets/61493780/91e37fa3-a168-4f10-9f1b-b16e7917c8e2)
而由于这个操作是在服务器上发生的，所以即使我本地网络没有问题，此时即使手动重新上传也仍还是大概率失败
对此有什么解决方法吗
附甲骨文日本到国内丢包情况（可以说是惨不忍睹
![image](https://github.com/sy-records/sync-qcloud-cos/assets/61493780/ccb92891-fce1-4562-8d00-4446e91183cb)

**Comment by sy-records** [comment]
北京的还行吗？可以换个桶地域看看。

这个问题可以提个腾讯工单，看他们有什么建议

**Comment by MIKU-N** [comment]
> 北京的还行吗？可以换个桶地域看看。
> 
> 这个问题可以提个腾讯工单，看他们有什么建议

换了北京的尝试了一下，还是会高概率失败
至于腾讯云那边，直接甩锅运营商跨境网络
![image](https://github.com/sy-records/sync-qcloud-cos/assets/61493780/02f00380-8d3e-48a8-a467-4f04c76db993)
我想问问是否能给插件增加一个失败重试的机制？或许会好些？

**Comment by MIKU-N** [comment]
> 治标不治本，重试也可能会失败。
> 
> 曲线救国：试试腾讯云的回源功能，读取不到让腾讯云自己拉取并存储。

不曲线了，最后的结果是直接加钱，开启了全球加速功能后正常上传了，就是流量小贵，1.5元/GB
