### ISSUE TITLE
上传到oss很慢

### ISSUE THREAD

**Issue by c1pyerten** [sy-records/sync-qcloud-cos#49]
上传至服务器速度都是正常的, 服务器和oss是同一地域

不太懂wordpress.. 不知道怎么排查

![image](https://github.com/sy-records/sync-qcloud-cos/assets/17029103/ba180b9e-fbe9-427e-b0d8-eff300bb340b)

如图... 上传100%后等了比较久的时间oss才上传完毕, oss本身不应该是这个速度的.

**Comment by sy-records** [comment]
视频文件有多大呢？

---
🤔 这是cos，oss是阿里云的。

**Comment by sy-records** [comment]
fpm的执行超时时间调大点试试，可以再试试写个测试文件，调用sdk，通过同样的方式上传看看结果

**Comment by sy-records** [comment]
先关闭了，有结果或者继续跟进的话可以继续回复
