### ISSUE TITLE
网站排版错误

### ISSUE THREAD

**Issue by yjiawqgj** [sy-records/sync-qcloud-cos#51]
使用插件把文件同步后，替换数据库https://www.xx.com/wp-content/uploads/2022为https://img.xx.com/wp-content/uploads/2022,这样就避免把css也上传到cos，但是这样替换后，打开网站还出现了https://img.xx.com/wp-content/uploads/blocks这样的链接？

**Comment by sy-records** [comment]
和插件无关，blocks目录可能是wp或者是主题写的，替换数据库也不会创建这个目录。

同步不区分目录，所有uploads都会上传。

**Comment by yjiawqgj** [comment]
> 和插件无关，blocks目录可能是wp或者是主题写的，替换数据库也不会创建这个目录。
> 
> 同步不区分目录，所有uploads都会上传。

但是我数据库替换到具体年份了，他不应该出现blocksy这个目录呀。而且你这个如果把所有uploads目录上传到cos，那css文件也会被目录，如果我更新插件或者主题的css，cos不会自动更新，那样客户端会看不到更新的呀！

**Comment by sy-records** [comment]
那你需要检查这个 blocks 是怎么生成的，链接是读的配置项拼接的。
