### ISSUE TITLE
自定义域名失效

### ISSUE THREAD

**Issue by Mdreame** [sy-records/sync-qcloud-cos#55]
已配置
- WordPress上传路径：wp-content/uploads
- 自定义域名：example.com

预期访问资源的链接是 example.com/<filename> ，以前上传的资源在WordPress后台可以正常显示。

但是今天突然失效了，检查腾讯云COS存储桶发现又自动创建了 wp-content/uploads 路径。

新上传的图片不显示预览，必须以 example.com/wp-content/uploads/<filename> 才可访问。

重新安装后仍然无效。

**Comment by sy-records** [comment]
插件一直支持的是自定义域名中需要包含上传路径，也就是url前缀的配置项需要填写为`http://example.com/wp-content/uploads`这种的。

如果你要保存在根目录，那上传路径就配置为`.`

**Comment by Mdreame** [comment]
> 插件一直支持的是自定义域名中需要包含上传路径，也就是url前缀的配置项需要填写为`http://example.com/wp-content/uploads`这种的。
> 
> 如果你要保存在根目录，那上传路径就配置为`.`

![image](https://github.com/sy-records/sync-qcloud-cos/assets/21331592/e6b7ec26-1693-47e1-a29b-ac34e0fa1429)
是这样配置对吧？ 你说的上传路径就是这里的本地文件夹。

我以为**本地文件夹**必须填 wp-content/uploads ，从这里读取数据。

现在行了, 关闭了。多谢你。
