### ISSUE TITLE
出现了新的报错

### ISSUE THREAD

**Issue by huanfeng123** [sy-records/sync-qcloud-cos#59]
wp版本：6.4.2 版本

插件版本：2.4.1

在保存配置时出现错误代码：

**Comment by huanfeng123** [comment]
> wp版本：6.4.2 版本
> 
> 插件版本：2.4.1
> 
> 在保存配置时出现错误代码：

`GuzzleHttp\Exception\ConnectException: cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://xxfdh-1258615817.cos.ap-hongkong.myqcloud.com/ in /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210 Stack trace: #0 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection() #1 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError() #2 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(250): GuzzleHttp\Handler\CurlFactory::finish() #3 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(174): GuzzleHttp\Handler\CurlMultiHandler->processMessages() #4 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(189): GuzzleHttp\Handler\CurlMultiHandler->tick() #5 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Handler\CurlMultiHandler->execute() #6 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn() #7 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending() #8 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList() #9 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending() #10 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Coroutine.php(68): GuzzleHttp\Promise\Promise->wait() #11 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}() #12 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn() #13 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending() #14 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Coroutine.php(100): GuzzleHttp\Promise\Promise->wait() #15 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(78): GuzzleHttp\Promise\Coroutine->wait() #16 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(157): GuzzleHttp\Command\ServiceClient->execute() #17 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/qcloud/cos-sdk-v5/src/Client.php(422): GuzzleHttp\Command\ServiceClient->__call() #18 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/sync-qcloud-cos.php(103): Qcloud\Cos\Client->__call() #19 /www/wwwroot/htmlai.cn/wp-content/plugins/sync-qcloud-cos/sync-qcloud-cos.php(1406): cos_check_bucket() #20 /www/wwwroot/htmlai.cn/wp-includes/class-wp-hook.php(324): cos_setting_page() #21 /www/wwwroot/htmlai.cn/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #22 /www/wwwroot/htmlai.cn/wp-includes/plugin.php(517): WP_Hook->do_action() #23 /www/wwwroot/htmlai.cn/wp-admin/admin.php(259): do_action() #24 {main}`

**Comment by sy-records** [comment]
curl error 7

和插件无关，检查你环境的问题
