### ISSUE TITLE
MIME  Bug

### ISSUE THREAD

**Issue by djerryz** [sy-records/sync-qcloud-cos#70]
感谢开源这个优秀的项目,  最近文件上传遇到下述问题:

![image](https://github.com/sy-records/sync-qcloud-cos/assets/24947060/fa5b44d5-1eed-468e-9d29-74f1b309c8b9)

```
Warning: Undefined array key "jpg|jpeg|jpe" in /var/www/html/wp-content/plugins/sync-qcloud-cos/sync-qcloud-cos.php on line 360 Warning: Undefined array key "gif" in /var/www/html/wp-content/plugins/sync-qcloud-cos/sync-qcloud-cos.php on line 361 Warning: Undefined array key "bmp" in /var/www/html/wp-content/plugins/sync-qcloud-cos/sync-qcloud-cos.php on line 363 Warning: Undefined array key "tiff|tif" in /var/www/html/wp-content/plugins/sync-qcloud-cos/sync-qcloud-cos.php on line 364 Warning: Undefined array key "webp" in /var/www/html/wp-content/plugins/sync-qcloud-cos/sync-qcloud-cos.php on line 365 Warning: Undefined array key "ico" in /var/www/html/wp-content/plugins/sync-qcloud-cos/sync-qcloud-cos.php on line 366 3401
```

我解决了这个问题:
modify`$mime_types = get_allowed_mime_types();` to  `$mime_types = wp_get_mime_types();`

**Comment by sy-records** [comment]
get_allowed_mime_types 也是调用的 wp_get_mime_types，可能是你当前登录用户权限不够被过滤了？

https://developer.wordpress.org/reference/functions/get_allowed_mime_types/
https://developer.wordpress.org/reference/functions/wp_get_mime_types/

不过用wp_get_mime_types也行

**Comment by djerryz** [comment]
挺奇怪的，之前没有出现过这个情况，我使用的是管理员权限登录的，怀疑是做了环境迁移带来的bug
