### ISSUE TITLE
保存报错

### ISSUE THREAD

**Issue by baivbai** [sy-records/sync-qcloud-cos#73]
保存配置的时候报错，发现
Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /var/www/html/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/functions.php:61 Stack trace: #0 /var/www/html/wp-...
这样子，发现可能是和BackWPup这个备份插件冲突，停掉BackWPup就正常了。

**Comment by sy-records** [comment]
是的，和使用 Guzzle 低版本的插件有冲突，
